apiVersion: apps/v1
kind: Deployment
metadata:
 name: javawebapp-deploy
 labels:
   app: javawebapp
spec:
 replicas: 2
 selector:
   matchLabels:
    app: javawebapp
 template:
    metadata:
      name:  javawebapp-pod
      labels:
        app: javawebapp
        tier: dev
    spec:
      containers:
      - name: javawebapp-container
        image: docker89781/java-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

------
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  selector:
    app: javawebapp
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer