apiVersion: apps/v1
kind: Deployment
metadata:
 name: javawebapp
 labels:
   app: javawebapp
spec:
 replicas: 2
 selector:
   matchLabels:
    app: javawebapp
 template:
    metadata:
      name:  javawebapp-pod
      labels:
        app: javawebapp
        tier: dev
    spec:
      containers:
      - name: javawebapp
        image: docker89781/java-app:#{}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
