apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
    
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 8080